<a href="https://colab.research.google.com/github/joyangelai/Colabs-Vol-2/blob/main/Encoding_%26_Model_creation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import necessary libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [ ]:
# load dataset
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [ ]:
## Using one hot encoder
enc = OneHotEncoder()
enc.fit_transform(df[['embark_town']]).toarray()

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       ...,
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [ ]:
enc.categories_ #this labels the array columns

[array(['Cherbourg', 'Queenstown', 'Southampton', nan], dtype=object)]

In [ ]:
# Another method encode using get_dummies
# Drop-first to avoid multicollinearity / complex model / overfitting
enc1 = pd.get_dummies(df[['embark_town','embarked']],drop_first=True,dtype=int)
enc1

,embark_town_Queenstown,embark_town_Southampton,embarked_Q,embarked_S
0,0,1,0,1
1,0,0,0,0
2,0,1,0,1
3,0,1,0,1
4,0,1,0,1
...,...,...,...,...
886,0,1,0,1
887,0,1,0,1
888,0,1,0,1
889,0,0,0,0


In [ ]:
# dealing with null values
df.isnull().sum()

,0
survived,0
pclass,0
sex,0
age,177
sibsp,0
parch,0
fare,0
embarked,2
class,0
who,0


In [ ]:
# dropping null values
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

,0
survived,0
pclass,0
sex,0
age,0
sibsp,0
parch,0
fare,0
embarked,0
class,0
who,0


In [ ]:
# encoding --> always use drop_first
enc2 =  pd.get_dummies(df[['sex']],drop_first=True,dtype=int)
enc2

,sex_male
1,0
3,0
6,1
10,0
11,0
...,...
871,0
872,1
879,0
887,0


In [ ]:
# using get dummies
enc3 = pd.get_dummies(df[['deck']], drop_first=True, dtype=int)
enc3

,deck_B,deck_C,deck_D,deck_E,deck_F,deck_G
1,0,1,0,0,0,0
3,0,1,0,0,0,0
6,0,0,0,1,0,0
10,0,0,0,0,0,1
11,0,1,0,0,0,0
...,...,...,...,...,...,...
871,0,0,1,0,0,0
872,1,0,0,0,0,0
879,0,1,0,0,0,0
887,1,0,0,0,0,0


In [ ]:
# using Label Encoder - hierarchy(order)
label1 = LabelEncoder()

labelen = label1.fit_transform(df[['class']])
np.ravel(labelen)    # still has a problem! Tr. will solve it later

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [ ]:
# Another method encode using get_dummies
# Drop-first to avoid multicollinearity / complex model / overfitting
enc1 = pd.get_dummies(df[['embark_town','embarked','sex']],drop_first=True,dtype=int)
enc1

,embark_town_Queenstown,embark_town_Southampton,embarked_Q,embarked_S,sex_male
1,0,0,0,0,0
3,0,1,0,1,0
6,0,1,0,1,1
10,0,1,0,1,0
11,0,1,0,1,0
...,...,...,...,...,...
871,0,1,0,1,0
872,0,1,0,1,1
879,0,0,0,0,0
887,0,1,0,1,0


In [ ]:
merged_df = pd.concat([df,enc1],axis=1)
merged_df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,embark_town_Queenstown,embark_town_Southampton,embarked_Q,embarked_S,sex_male
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,0,0,0,0,0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0,1,0,1,0
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True,0,1,0,1,1
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False,0,1,0,1,0
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True,0,1,0,1,0


In [ ]:
# dropping original columns
merged_df.drop(['embark_town','embarked','sex'], axis=1,inplace=True)

In [ ]:
merged_df.head()

,survived,pclass,age,sibsp,parch,fare,class,who,adult_male,deck,alive,alone,embark_town_Queenstown,embark_town_Southampton,embarked_Q,embarked_S,sex_male
1,1,1,38.0,1,0,71.2833,First,woman,False,C,yes,False,0,0,0,0,0
3,1,1,35.0,1,0,53.1000,First,woman,False,C,yes,False,0,1,0,1,0
6,0,1,54.0,0,0,51.8625,First,man,True,E,no,True,0,1,0,1,1
10,1,3,4.0,1,1,16.7000,Third,child,False,G,yes,False,0,1,0,1,0
11,1,1,58.0,0,0,26.5500,First,woman,False,C,yes,True,0,1,0,1,0


In [ ]:
# loading homeprice dataset
data = pd.read_csv("/content/drive/MyDrive/homeprices.csv")
data.head()

,town,area,price
0,monroe township,2600,550000
1,monroe township,3000,565000
2,monroe township,3200,610000
3,monroe township,3600,680000
4,monroe township,4000,725000


In [ ]:
# encoding using get dummies
end = pd.get_dummies(data['town'], drop_first=True, dtype=int)
end.head()

,robinsville,west windsor
0,0,0
1,0,0
2,0,0
3,0,0
4,0,0


In [ ]:
merged_df = pd.concat([data, end], axis=1)
merged_df

,town,area,price,robinsville,west windsor
0,monroe township,2600,550000,0,0
1,monroe township,3000,565000,0,0
2,monroe township,3200,610000,0,0
3,monroe township,3600,680000,0,0
4,monroe township,4000,725000,0,0
5,west windsor,2600,585000,0,1
6,west windsor,2800,615000,0,1
7,west windsor,3300,650000,0,1
8,west windsor,3600,710000,0,1
9,robinsville,2600,575000,1,0


In [ ]:
# drop town column
del merged_df['town']
merged_df.head()

,area,price,robinsville,west windsor
0,2600,550000,0,0
1,3000,565000,0,0
2,3200,610000,0,0
3,3600,680000,0,0
4,4000,725000,0,0


In [ ]:
# divide data into 2 (features and label)
# X is our features/independent variables
X = merged_df.drop('price', axis=1)
X

,area,robinsville,west windsor
0,2600,0,0
1,3000,0,0
2,3200,0,0
3,3600,0,0
4,4000,0,0
5,2600,0,1
6,2800,0,1
7,3300,0,1
8,3600,0,1
9,2600,1,0


In [ ]:
# dependent/labe;
y = merged_df['price']

In [ ]:
# importing the model
from sklearn.linear_model import LinearRegression

In [ ]:
# call/initialise the model
model = LinearRegression()

# train the model
model.fit(X,y)

LinearRegression()

In [ ]:
# predict the model
model.predict(X)

array([539709.7398409 , 590468.71640507, 615848.20468716, 666607.18125134,
       717366.15781552, 579723.71533004, 605103.20361213, 668551.92431735,
       706621.15674048, 565396.1513653 , 603465.38378843, 628844.87207052,
       692293.59277575])

In [ ]:
merged_df['price']

,price
0,550000
1,565000
2,610000
3,680000
4,725000
5,585000
6,615000
7,650000
8,710000
9,575000


In [ ]:
# checking accuracy - how well the model is doing
print(round(model.score(X,y),4))

0.9574


In [ ]:
# trying to predict -- > this is new data we're trying to put our model in practice (unseen data)
model.predict([[5000, 1, 0]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([869950.01075037])